### PR TITLE
Streaming Movie Ratings for Kubernetes

### LINKED ISSUE #62: Streaming Movie ratings: Docker and Kubernetes support
Add support of

* [x] add uberjar packaging 
* [x] Docker packaging (separate project with docker / jib configuration)
* [x] Kubernetes deployment with `Deployment` and `StatefulSet`
* [ ] Add helm chart for Kubernetes deployment

cc @tlberglund

### PR DESCRIPTION
**Pull request by gAmUssA**
FIXES #62

### CODE REVIEW

**Comment by tlberglund** [comment]
Don't have time to review terribly thoroughly today, but riddle me this: can I still use this demo without using k8s?

**Comment by gAmUssA** [comment]
@tlberglund Yes, docker thingy is Kubernetes agnostic. you still can use this demo with local CP, CCP, and CCE.
I'm adding new stuff here, not removing new stuff.

**Comment by gAmUssA** [comment]
@ybyzek it does. I demoed it in Raleigh Kafka Meetup ;-P

**Comment by tlberglund** [comment]
I can't test this right now, but I can give my approval in principle to the addition.

**Pull request merged**
