### PR TITLE
Tiered Storage Demo

### PR DESCRIPTION
**Pull request by mattwong949**
Adding a demo for Tiered Storage Preview in CP 5.4

### CODE REVIEW

**Comment by rmoff** [comment]
Thanks for the PR! Please add an entry to the repo index /README.adoc

**Comment by rmoff** [comment]
This looks great @mattwong949. My only issue is the Docker image used (`5.4.0-SNAPSHOT`) - I don't think we should publish to a public repo something that's not available. How about changing the Docker Compose to use 5.4.0 (and you can test it by re-tagging your 5.4.0-SNAPSHOT locally to 5.4.0) and then we can merge the PR as soon as 5.4.0 drops?

**Comment by mattwong949** [comment]
> This looks great @mattwong949. My only issue is the Docker image used (`5.4.0-SNAPSHOT`) - I don't think we should publish to a public repo something that's not available. How about changing the Docker Compose to use 5.4.0 (and you can test it by re-tagging your 5.4.0-SNAPSHOT locally to 5.4.0) and then we can merge the PR as soon as 5.4.0 drops?

@rmoff Thanks for taking a look! I changed the image tag to 5.4.0

**Comment by rmoff** [comment]
💥 thanks @mattwong949 !

**Pull request merged**
